module.exports = {
  parser: 'babel-eslint',
  extends: ['airbnb', 'plugin:compat/recommended'],
  // extends: ['airbnb', 'prettier', 'plugin:compat/recommended'],
  env: {
    browser: true,
    node: true,
    es6: true,
    mocha: true,
    jest: true,
    jasmine: true,
  },
  globals: {
    APP_TYPE: true,
  },
  settings: {
    polyfills: ['fetch', 'promises', 'url'],
  },
  rules: {
    'react/jsx-filename-extension': [1, { extensions: ['.js'] }],
    'react/jsx-wrap-multilines': 0,
    'react/prop-types': 0,
    'react/forbid-prop-types': 0,
    'react/jsx-one-expression-per-line': 0,
    'import/no-unresolved': [2, { ignore: ['^@/', '^umi/'] }],
    'import/no-extraneous-dependencies': [2, { optionalDependencies: true }],
    'jsx-a11y/no-noninteractive-element-interactions': 0,
    'jsx-a11y/click-events-have-key-events': 0,
    'jsx-a11y/no-static-element-interactions': 0,
    'jsx-a11y/anchor-is-valid': 0,

    'generator-star-spacing': 0,
    'object-curly-newline': 0,
    'arrow-body-style': 0,
    'no-unused-expressions': 0,
    'prefer-promise-reject-errors': 0,
    'react/no-find-dom-node': 0,
    'react/no-array-index-key': 0,
    'max-len': 0,
    'no-return-assign': 0,
    'prefer-destructuring': 0,
    'no-underscore-dangle': 0,
    'dot-notation': 0,
    'quote-props': 0,
    'no-unreachable': 0,
    'no-throw-literal': 0,
    'react/destructuring-assignment': 0,
    'global-require': 0,
    'react/no-unused-state': 1,
    'camelcase': 0,
    'comma-dangle': [2, 'never'],
    "no-param-reassign": 0,
    "operator-linebreak": 0
  },
};
